#YourName.py
name = input("What is your name?\n")
print("Hi, ", name) 
FavoriteColor  = input("What is your favorite color?\n")
HowDoing = input("How are you?\n")
FavoriteAnimal = input("What is your favorite animal?\n")
FavoritePottyWord = input("What is your favorite potty verb that ends in -ed?\n")
FavoriteShape = input("What is your favorite shape?\n")
FavoriteActionVerb = input("What is your favorite action verb?\n")
FavoriteNoun = input("What is your favorete noun?\n")
Favoritedesert = input("What is your Favorite desert?\n")
